# Default values for chart

service:
  type: LoadBalancer
  port: 5000

deploy:
  name: flask-tf
  replicas: 3
  acrServer: briaracreu.azurecr.io
  image: chzbrgr71/edsheeran-flask-app
  imageTag: 2.0
  containerPort: 5000