apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-tf
spec:
  replicas: {{ default 1 .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: flask-tf
  template:
    metadata:
      labels:
        app: flask-tf
    spec:
      containers:
        - image: {{.Values.deploy.image}}:{{.Values.deploy.imageTag}}
          imagePullPolicy: Always
          name: flask-tf
          ports:
          - containerPort: 5000
            protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flask-tf
  labels:
    name: flask-tf
spec:
  type: "{{.Values.service.type}}"
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: flask-tf
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-tf
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: "{{.Values.service.ingressDNSName}}"
    http:
      paths:
      - backend:
          serviceName: flask-tf
          servicePort: 5000
        path: /detect_image